server: dev@izenesoft.cn
remote_path: /data/sf1r-resource
local_path: ./package/resource
branch: kite-2
branch_suffix: resource
sub_modules:
    - ise
    - kpe
    - nec
    - opinion
    - product-matcher
    - qa
    - qn
    - sim
    - speller-support
    - spu-classifier
    - wikigraph
    - dict
push_sub_modules:
    - ise
    - kpe
    - nec
    - opinion
    - qa
    - dict
