sf1:
  ip: localhost
  port: 8888

# if empty, requests from all uris would be sent
uri:
  #- documents/search
  #- documents/index
  #- documents/

# if empty, requests from all collections would be sent
collection:
  #- b5mp
